version: '3.6'

services:
   web:
      image: josefjebavy/debian-apache-php8.1-nette
      container_name: import-doi-app
      working_dir: /var/www/html
      environment:
         - NETTE_DEBUG=1
      volumes:
         - .:/var/www/html
      ports:
         - 8081:80
         - 8082:443